/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GameInfo {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'maxWinnings' : bigint,
  'entryFee' : bigint,
}
export interface RevenueStats {
  'totalActiveGames' : bigint,
  'totalPaidOut' : bigint,
  'totalUsers' : bigint,
  'totalRevenue' : bigint,
  'netProfit' : bigint,
}
export type Time = bigint;
export interface Transaction {
  'id' : bigint,
  'userId' : Principal,
  'note' : string,
  'gameId' : [] | [bigint],
  'timestamp' : Time,
  'txType' : TxType,
  'amount' : bigint,
}
export type TxType = { 'WithdrawalRejected' : null } |
  { 'Deposit' : null } |
  { 'GameEntry' : null } |
  { 'Bonus' : null } |
  { 'GameWin' : null } |
  { 'Withdrawal' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WalletInfo {
  'balance' : bigint,
  'totalInvested' : bigint,
  'owner' : Principal,
  'joinTime' : Time,
  'totalEarned' : bigint,
}
export interface WithdrawalInfo {
  'id' : bigint,
  'status' : WithdrawalStatus,
  'userId' : Principal,
  'processedAt' : [] | [Time],
  'amount' : bigint,
  'requestedAt' : Time,
}
export type WithdrawalStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Pending' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  /**
   * / Add a new game (admin).
   */
  'adminAddGame' : ActorMethod<[string, string, bigint, bigint], bigint>,
  /**
   * / List all registered users (admin).
   */
  'adminGetAllUsers' : ActorMethod<[], Array<WalletInfo>>,
  'adminGetRevenueStats' : ActorMethod<[], RevenueStats>,
  /**
   * / Get a specific user's wallet and recent transactions (admin).
   */
  'adminGetUserDetails' : ActorMethod<
    [Principal],
    [] | [[WalletInfo, Array<Transaction>]]
  >,
  /**
   * / Update an existing game (admin).
   */
  'adminUpdateGame' : ActorMethod<
    [bigint, string, string, bigint, bigint, boolean],
    boolean
  >,
  /**
   * / Approve a withdrawal request (admin).
   */
  'approveWithdrawal' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Get caller's wallet info.
   */
  'getMyWallet' : ActorMethod<[], [] | [WalletInfo]>,
  /**
   * / Get caller's transaction history.
   */
  'getTransactionHistory' : ActorMethod<[], Array<Transaction>>,
  /**
   * / Returns true if the caller is an admin.
   */
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / List all active games (public).
   */
  'listActiveGames' : ActorMethod<[], Array<GameInfo>>,
  /**
   * / List all pending withdrawals (admin).
   */
  'listPendingWithdrawals' : ActorMethod<[], Array<WithdrawalInfo>>,
  /**
   * / Play a game — deducts entry fee from wallet; returns session id.
   */
  'playGame' : ActorMethod<[bigint], bigint>,
  /**
   * / Admin records game result; credits winnings if won.
   */
  'recordGameResult' : ActorMethod<[bigint, boolean, bigint], undefined>,
  /**
   * / Register new user — creates wallet and gives 10 paisa signup bonus.
   */
  'registerUser' : ActorMethod<[], WalletInfo>,
  /**
   * / Reject a withdrawal request — returns balance to user (admin).
   */
  'rejectWithdrawal' : ActorMethod<[bigint], undefined>,
  /**
   * / Request a withdrawal (minimum 1 paisa).
   */
  'requestWithdrawal' : ActorMethod<[bigint], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];