/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const WalletInfo = IDL.Record({
  'balance' : IDL.Nat,
  'totalInvested' : IDL.Nat,
  'owner' : IDL.Principal,
  'joinTime' : Time,
  'totalEarned' : IDL.Nat,
});
export const RevenueStats = IDL.Record({
  'totalActiveGames' : IDL.Nat,
  'totalPaidOut' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
  'netProfit' : IDL.Nat,
});
export const TxType = IDL.Variant({
  'WithdrawalRejected' : IDL.Null,
  'Deposit' : IDL.Null,
  'GameEntry' : IDL.Null,
  'Bonus' : IDL.Null,
  'GameWin' : IDL.Null,
  'Withdrawal' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'note' : IDL.Text,
  'gameId' : IDL.Opt(IDL.Nat),
  'timestamp' : Time,
  'txType' : TxType,
  'amount' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const GameInfo = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'maxWinnings' : IDL.Nat,
  'entryFee' : IDL.Nat,
});
export const WithdrawalStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'Pending' : IDL.Null,
});
export const WithdrawalInfo = IDL.Record({
  'id' : IDL.Nat,
  'status' : WithdrawalStatus,
  'userId' : IDL.Principal,
  'processedAt' : IDL.Opt(Time),
  'amount' : IDL.Nat,
  'requestedAt' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'adminAddGame' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'adminGetAllUsers' : IDL.Func([], [IDL.Vec(WalletInfo)], ['query']),
  'adminGetRevenueStats' : IDL.Func([], [RevenueStats], ['query']),
  'adminGetUserDetails' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Tuple(WalletInfo, IDL.Vec(Transaction)))],
      ['query'],
    ),
  'adminUpdateGame' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Bool],
      [IDL.Bool],
      [],
    ),
  'approveWithdrawal' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyWallet' : IDL.Func([], [IDL.Opt(WalletInfo)], ['query']),
  'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listActiveGames' : IDL.Func([], [IDL.Vec(GameInfo)], ['query']),
  'listPendingWithdrawals' : IDL.Func([], [IDL.Vec(WithdrawalInfo)], ['query']),
  'playGame' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'recordGameResult' : IDL.Func([IDL.Nat, IDL.Bool, IDL.Nat], [], []),
  'registerUser' : IDL.Func([], [WalletInfo], []),
  'rejectWithdrawal' : IDL.Func([IDL.Nat], [], []),
  'requestWithdrawal' : IDL.Func([IDL.Nat], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const WalletInfo = IDL.Record({
    'balance' : IDL.Nat,
    'totalInvested' : IDL.Nat,
    'owner' : IDL.Principal,
    'joinTime' : Time,
    'totalEarned' : IDL.Nat,
  });
  const RevenueStats = IDL.Record({
    'totalActiveGames' : IDL.Nat,
    'totalPaidOut' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
    'netProfit' : IDL.Nat,
  });
  const TxType = IDL.Variant({
    'WithdrawalRejected' : IDL.Null,
    'Deposit' : IDL.Null,
    'GameEntry' : IDL.Null,
    'Bonus' : IDL.Null,
    'GameWin' : IDL.Null,
    'Withdrawal' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'note' : IDL.Text,
    'gameId' : IDL.Opt(IDL.Nat),
    'timestamp' : Time,
    'txType' : TxType,
    'amount' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const GameInfo = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'maxWinnings' : IDL.Nat,
    'entryFee' : IDL.Nat,
  });
  const WithdrawalStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const WithdrawalInfo = IDL.Record({
    'id' : IDL.Nat,
    'status' : WithdrawalStatus,
    'userId' : IDL.Principal,
    'processedAt' : IDL.Opt(Time),
    'amount' : IDL.Nat,
    'requestedAt' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'adminAddGame' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'adminGetAllUsers' : IDL.Func([], [IDL.Vec(WalletInfo)], ['query']),
    'adminGetRevenueStats' : IDL.Func([], [RevenueStats], ['query']),
    'adminGetUserDetails' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Tuple(WalletInfo, IDL.Vec(Transaction)))],
        ['query'],
      ),
    'adminUpdateGame' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Bool],
        [IDL.Bool],
        [],
      ),
    'approveWithdrawal' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyWallet' : IDL.Func([], [IDL.Opt(WalletInfo)], ['query']),
    'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listActiveGames' : IDL.Func([], [IDL.Vec(GameInfo)], ['query']),
    'listPendingWithdrawals' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalInfo)],
        ['query'],
      ),
    'playGame' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'recordGameResult' : IDL.Func([IDL.Nat, IDL.Bool, IDL.Nat], [], []),
    'registerUser' : IDL.Func([], [WalletInfo], []),
    'rejectWithdrawal' : IDL.Func([IDL.Nat], [], []),
    'requestWithdrawal' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };