/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface WithdrawalInfo {
    id: bigint;
    status: WithdrawalStatus;
    userId: Principal;
    processedAt?: Time;
    amount: bigint;
    requestedAt: Time;
}
export type Time = bigint;
export interface GameInfo {
    id: bigint;
    name: string;
    description: string;
    isActive: boolean;
    maxWinnings: bigint;
    entryFee: bigint;
}
export interface WalletInfo {
    balance: bigint;
    totalInvested: bigint;
    owner: Principal;
    joinTime: Time;
    totalEarned: bigint;
}
export interface RevenueStats {
    totalActiveGames: bigint;
    totalPaidOut: bigint;
    totalUsers: bigint;
    totalRevenue: bigint;
    netProfit: bigint;
}
export interface Transaction {
    id: bigint;
    userId: Principal;
    note: string;
    gameId?: bigint;
    timestamp: Time;
    txType: TxType;
    amount: bigint;
}
export enum TxType {
    WithdrawalRejected = "WithdrawalRejected",
    Deposit = "Deposit",
    GameEntry = "GameEntry",
    Bonus = "Bonus",
    GameWin = "GameWin",
    Withdrawal = "Withdrawal"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum WithdrawalStatus {
    Approved = "Approved",
    Rejected = "Rejected",
    Pending = "Pending"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    /**
     * / Add a new game (admin).
     */
    adminAddGame(name: string, description: string, entryFee: bigint, maxWinnings: bigint): Promise<bigint>;
    /**
     * / List all registered users (admin).
     */
    adminGetAllUsers(): Promise<Array<WalletInfo>>;
    adminGetRevenueStats(): Promise<RevenueStats>;
    /**
     * / Get a specific user's wallet and recent transactions (admin).
     */
    adminGetUserDetails(userId: Principal): Promise<[WalletInfo, Array<Transaction>] | null>;
    /**
     * / Update an existing game (admin).
     */
    adminUpdateGame(id: bigint, name: string, description: string, entryFee: bigint, maxWinnings: bigint, isActive: boolean): Promise<boolean>;
    /**
     * / Approve a withdrawal request (admin).
     */
    approveWithdrawal(id: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Get caller's wallet info.
     */
    getMyWallet(): Promise<WalletInfo | null>;
    /**
     * / Get caller's transaction history.
     */
    getTransactionHistory(): Promise<Array<Transaction>>;
    /**
     * / Returns true if the caller is an admin.
     */
    isAdmin(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / List all active games (public).
     */
    listActiveGames(): Promise<Array<GameInfo>>;
    /**
     * / List all pending withdrawals (admin).
     */
    listPendingWithdrawals(): Promise<Array<WithdrawalInfo>>;
    /**
     * / Play a game — deducts entry fee from wallet; returns session id.
     */
    playGame(gameId: bigint): Promise<bigint>;
    /**
     * / Admin records game result; credits winnings if won.
     */
    recordGameResult(sessionId: bigint, didWin: boolean, winAmount: bigint): Promise<void>;
    /**
     * / Register new user — creates wallet and gives 10 paisa signup bonus.
     */
    registerUser(): Promise<WalletInfo>;
    /**
     * / Reject a withdrawal request — returns balance to user (admin).
     */
    rejectWithdrawal(id: bigint): Promise<void>;
    /**
     * / Request a withdrawal (minimum 1 paisa).
     */
    requestWithdrawal(amount: bigint): Promise<bigint>;
}
import type { Time as _Time, Transaction as _Transaction, TxType as _TxType, UserRole as _UserRole, WalletInfo as _WalletInfo, WithdrawalInfo as _WithdrawalInfo, WithdrawalStatus as _WithdrawalStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async adminAddGame(arg0: string, arg1: string, arg2: bigint, arg3: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAddGame(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAddGame(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async adminGetAllUsers(): Promise<Array<WalletInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllUsers();
            return result;
        }
    }
    async adminGetRevenueStats(): Promise<RevenueStats> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetRevenueStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetRevenueStats();
            return result;
        }
    }
    async adminGetUserDetails(arg0: Principal): Promise<[WalletInfo, Array<Transaction>] | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetUserDetails(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetUserDetails(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateGame(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateGame(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateGame(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async approveWithdrawal(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveWithdrawal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveWithdrawal(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyWallet(): Promise<WalletInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyWallet();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyWallet();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionHistory(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionHistory();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionHistory();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listActiveGames(): Promise<Array<GameInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listActiveGames();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listActiveGames();
            return result;
        }
    }
    async listPendingWithdrawals(): Promise<Array<WithdrawalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPendingWithdrawals();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPendingWithdrawals();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async playGame(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.playGame(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.playGame(arg0);
            return result;
        }
    }
    async recordGameResult(arg0: bigint, arg1: boolean, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordGameResult(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordGameResult(arg0, arg1, arg2);
            return result;
        }
    }
    async registerUser(): Promise<WalletInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser();
            return result;
        }
    }
    async rejectWithdrawal(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectWithdrawal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectWithdrawal(arg0);
            return result;
        }
    }
    async requestWithdrawal(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.requestWithdrawal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestWithdrawal(arg0);
            return result;
        }
    }
}
function from_candid_Transaction_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_TxType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TxType): TxType {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalInfo_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalInfo): WithdrawalInfo {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalStatus): WithdrawalStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [[_WalletInfo, Array<_Transaction>]]): [WalletInfo, Array<Transaction>] | null {
    return value.length === 0 ? null : from_candid_tuple_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WalletInfo]): WalletInfo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _WithdrawalStatus;
    userId: Principal;
    processedAt: [] | [_Time];
    amount: bigint;
    requestedAt: _Time;
}): {
    id: bigint;
    status: WithdrawalStatus;
    userId: Principal;
    processedAt?: Time;
    amount: bigint;
    requestedAt: Time;
} {
    return {
        id: value.id,
        status: from_candid_WithdrawalStatus_n17(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        processedAt: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.processedAt)),
        amount: value.amount,
        requestedAt: value.requestedAt
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    userId: Principal;
    note: string;
    gameId: [] | [bigint];
    timestamp: _Time;
    txType: _TxType;
    amount: bigint;
}): {
    id: bigint;
    userId: Principal;
    note: string;
    gameId?: bigint;
    timestamp: Time;
    txType: TxType;
    amount: bigint;
} {
    return {
        id: value.id,
        userId: value.userId,
        note: value.note,
        gameId: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.gameId)),
        timestamp: value.timestamp,
        txType: from_candid_TxType_n7(_uploadFile, _downloadFile, value.txType),
        amount: value.amount
    };
}
function from_candid_tuple_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_WalletInfo, Array<_Transaction>]): [WalletInfo, Array<Transaction>] {
    return [
        value[0],
        from_candid_vec_n3(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Approved: null;
} | {
    Rejected: null;
} | {
    Pending: null;
}): WithdrawalStatus {
    return "Approved" in value ? WithdrawalStatus.Approved : "Rejected" in value ? WithdrawalStatus.Rejected : "Pending" in value ? WithdrawalStatus.Pending : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    WithdrawalRejected: null;
} | {
    Deposit: null;
} | {
    GameEntry: null;
} | {
    Bonus: null;
} | {
    GameWin: null;
} | {
    Withdrawal: null;
}): TxType {
    return "WithdrawalRejected" in value ? TxType.WithdrawalRejected : "Deposit" in value ? TxType.Deposit : "GameEntry" in value ? TxType.GameEntry : "Bonus" in value ? TxType.Bonus : "GameWin" in value ? TxType.GameWin : "Withdrawal" in value ? TxType.Withdrawal : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WithdrawalInfo>): Array<WithdrawalInfo> {
    return value.map((x)=>from_candid_WithdrawalInfo_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n4(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
